# Generated by Django 3.2 on 2021-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Rollnumber', models.IntegerField(max_length=30, unique=True)),
                ('Dateofbirth', models.DateField()),
            ],
        ),
    ]
