# Generated by Django 3.2 on 2021-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Dateofbirth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Rollnumber',
            field=models.IntegerField(unique=True),
        ),
    ]
